# Generated by Django 5.0.4 on 2025-04-16 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_follow'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('user', 'user_follower')},
        ),
    ]
