# Generated by Django 5.0.4 on 2025-04-16 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_follow_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='user_follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_follower', to=settings.AUTH_USER_MODEL),
        ),
    ]
